#!/bin/bash
folders=(
     "$HOME/Documents"
     "$HOME/Dropbox"
     "$HOME/bin"
     "$HOME/Desktop"
     "$HOME/OneDrive - Calcopedia"
     #"$HOME/go/src"
)
DATE=`date +%Y-%m-%d`

# Check that they are directories
for Path in "${folders[@]}"
do
    if [ ! -d "$Path" ]; then
        echo "no such directory: $Path"
    fi
done

echo "This will perform a bcp of:"
for Path in "${folders[@]}"
do
    echo "  - $Path"
done
read -p "Should I go ahead (y/n)? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

echo "Starting bcp"

for Path in "${folders[@]}"
do
    echo "Starting Backup of $Path $DATE'"
    pk-put file --permanode --title="Backup of $Path $DATE" --tag=backup,bcp "$Path"
    echo "done"
done