#!/bin/bash

#az vm start -g ViktorCompute -n vc01
#echo "Connect to jupyter on https://dsvm2xbsj6v4iea76.northeurope.cloudapp.azure.com:8000/"
#ssh vron@dsvm2xbsj6v4iea76.northeurope.cloudapp.azure.com
export PROJECT_ID="deepart-259120"
export ZONE="europe-west1-b"
export INSTANCE_NAME="deep01-vm"

gcloud compute instances start --project $PROJECT_ID --zone $ZONE "deep01-vm"
# gcloud beta compute ssh --project $PROJECT_ID --zone $ZONE "deep01-vm"