#!/bin/bash

PORT=${1:-"6006"}

echo "Tunneling http:$PORT to  https://dsvm2xbsj6v4iea76.northeurope.cloudapp.azure.com"
ssh -L "0.0.0.0:$PORT:0.0.0.0:$PORT" vron@dsvm2xbsj6v4iea76.northeurope.cloudapp.azure.com